##eureka的服务地址
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9991/eureka/
#spring:
#  #服务名
#  application:
#    name: zuul
#server:
#  #端口号
#  port: 10001
#zuul:
#  #访问真实服务时，加一个前缀
#  prefix: /labi
#  #屏蔽掉以前的地址
#  ignored-services: "*"
#  #将city改为mycity
#  routes:
#    city:
#      path: /mycity/**
