spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dingdang1998/micro_config_rep.git
          default-label: main
server:
  port: 10010