server:
  port: 9991
eureka:
  client:
    #是否将自己注册到eureka中
    register-with-eureka: false
    #是否获取注册
    fetch-registry: false
    #eureka服务地址
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/